### ISSUE TITLE
一定要通过button生成海报吗

### ISSUE THREAD

**Issue by DXIAOdeng** [jasondu/wxa-plugin-canvas#204]
<button>点击生成海报</button> 一定要通过button生成海报吗  能不能不要

**Comment by yhuaqiang** [comment]
不需要发自我的iPhone------------------ 原始邮件 ------------------发件人: DXIAOdeng  <notifications@github.com>发送时间: 2020年4月13日 15:36收件人: jasondu/wxa-plugin-canvas <wxa-plugin-canvas@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[jasondu/wxa-plugin-canvas] 一定要通过button生成海报吗 (#204)
点击生成海报 一定要通过button生成海报吗  能不能不要

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasondu/wxa-plugin-canvas/issues/204",
"url": "https://github.com/jasondu/wxa-plugin-canvas/issues/204",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
